/**
 * Scenario: extractPixelStats samples a bounded set of pixels from an image
 * and reports ground-truth geometry and color facts for delegated visual
 * inspection (dimensions, distinct color count, dominant RGB + hex, flat/solid
 * detection, alpha usage), failing soft on undecodable input.
 *
 * Responsibilities: flat single-color detection, multi-color counting with the
 * most frequent color as dominant, alpha detection, sample bounding, and
 * null-on-garbage behavior. Wiring: real decode through the shared jimp path
 * (`decodeToJimp` in `image-compress`) with images generated by jimp. Run:
 * pnpm test -- test/agent/media/pixel-stats.test.ts
 */

import { describe, expect, it } from 'vitest';
import { Jimp } from 'jimp';

import { extractPixelStats } from '#/agent/media/pixel-stats';

describe('extractPixelStats', () => {
  it('reports a flat blue image with one distinct color, exact hex, and no alpha', async () => {
    const flat = Buffer.from(
      await new Jimp({ width: 3600, height: 1800, color: 0x3366ccff }).getBuffer('image/png'),
    );

    const stats = await extractPixelStats(flat, 'image/png');

    expect(stats).not.toBeNull();
    expect(stats!.width).toBe(3600);
    expect(stats!.height).toBe(1800);
    expect(stats!.sampledPixels).toBeGreaterThan(0);
    expect(stats!.sampledPixels).toBeLessThanOrEqual(200_000);
    expect(stats!.distinctColors).toBe(1);
    expect(stats!.flat).toBe(true);
    expect(stats!.hasAlpha).toBe(false);
    expect(stats!.dominantColor).toEqual({ r: 0x33, g: 0x66, b: 0xcc, hex: '#3366CC' });
  });

  it('counts distinct colors and picks the most frequent as dominant', async () => {
    const image = new Jimp({ width: 100, height: 100, color: 0xff0000ff });
    image.scan(0, 0, 10, 10, (_x, _y, idx) => {
      image.bitmap.data[idx] = 0x00;
      image.bitmap.data[idx + 1] = 0x00;
      image.bitmap.data[idx + 2] = 0xff;
      image.bitmap.data[idx + 3] = 0xff;
    });
    const png = await image.getBuffer('image/png');

    const stats = await extractPixelStats(png, 'image/png');

    expect(stats).not.toBeNull();
    expect(stats!.distinctColors).toBe(2);
    expect(stats!.flat).toBe(false);
    expect(stats!.hasAlpha).toBe(false);
    expect(stats!.dominantColor).toEqual({ r: 0xff, g: 0x00, b: 0x00, hex: '#FF0000' });
  });

  it('detects an alpha channel when non-opaque pixels are present', async () => {
    const semiTransparent = Buffer.from(
      await new Jimp({ width: 50, height: 50, color: 0x3366cc80 }).getBuffer('image/png'),
    );

    const stats = await extractPixelStats(semiTransparent, 'image/png');

    expect(stats).not.toBeNull();
    expect(stats!.hasAlpha).toBe(true);
    expect(stats!.distinctColors).toBe(1);
  });

  it('returns null for undecodable input', async () => {
    expect(await extractPixelStats(new Uint8Array([1, 2, 3]), 'image/png')).toBeNull();
  });

  it('returns null when the header parses but decoding fails', async () => {
    const fakePng = Buffer.alloc(24);
    fakePng.set([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a], 0);
    fakePng.writeUInt32BE(13, 8);
    fakePng.write('IHDR', 12, 'latin1');
    fakePng.writeUInt32BE(64, 16);
    fakePng.writeUInt32BE(64, 20);

    expect(await extractPixelStats(fakePng, 'image/png')).toBeNull();
  });
});
